### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by vyom-mate-labs** [nakumgaurav/XAI-TREPAN-for-Regression#1]
There is no file combined.csv, that you have mentioned in xai.py as dataset line 51.

Please help

**Comment by nakumgaurav** [comment]
Hi @vyom-mate-labs , thanks a lot for raising the issue. The dataset that the code was tested on was proprietary and cannot be shared. I will add an option to take a custom .csv file to run the code on. But you need to have your own dataset to test the code.

**Comment by nakumgaurav** [comment]
I have added the option the take your own dataset as input. Let me know if this works for you.

**Comment by vyom-mate-labs** [comment]
Thanks @nakumgaurav

**Comment by vyom-mate-labs** [comment]
Also I am getting the following error after training and node splits(line numbers might differ by a little):


Traceback (most recent call last):
  File "xai.py", line 515, in <module>
    root = tree_obj.build_tree()
  File "xai.py", line 362, in build_tree
    node, left_node, right_node = self.split(node)
  File "xai.py", line 419, in split
    left_ind = node.data[:, best_feat] <= best_split_point
TypeError: '<=' not supported between instances of 'float' and 'NoneType'



Also where are you defining the target variable?

**Comment by vyom-mate-labs** [comment]
Also, I think you are not plotting the graphs, only making the splits.
